Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "private_network", type: "dhcp" # в случае конфликта с существующим адаптером можно указать статический ip
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
