Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  
  config.vm.define "web" do |web|
    web.vm.hostname = "web"
    web.vm.network "private_network", ip: "192.168.56.10"
    web.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/web.yml"
      ansible.verbose = true
    end
  end

  config.vm.define "log" do |log|
    log.vm.hostname = "log"
    log.vm.network "private_network", ip: "192.168.56.11"
    log.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/log.yml"
      ansible.verbose = true
    end
  end
end